name: Pull External Sites

on:
  push:
    branches: [main]            # re‑deploy when the workflow itself changes
  workflow_dispatch:            # …or run by hand
  schedule:
    - cron: "0 6 * * SUN"       # …or every Sunday to catch late edits

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Remote sites in separate repositories
          - year: 2021
            type: static
          - year: 2023
            type: vite
          - year: 2024
            type: vite
    steps:
      - name: Checkout archive repo
        uses: actions/checkout@v4

      # Checkout external repository
      - name: Checkout year ${{ matrix.year }}
        uses: actions/checkout@v4
        with:
          repository: bccss/hth${{ matrix.year }}
          path: external-site

      # Install Node.js only for sites that need building
      - name: Set up Node.js
        if: matrix.type == 'vite'
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: external-site/package-lock.json

      # Build for modern sites
      - name: Install deps & build
        if: matrix.type == 'vite'
        working-directory: external-site
        run: |
          npm ci
          npm run build         # outputs to external-site/dist (for Vite)

      # Copy content to the year directory
      - name: Copy static site
        if: matrix.type == 'static'
        run: |
          mkdir -p ${{ matrix.year }}
          cp -r external-site/* ${{ matrix.year }}/

      # Copy for modern sites 
      - name: Copy built site
        if: matrix.type == 'vite'
        run: |
          mkdir -p ${{ matrix.year }}
          cp -r external-site/dist/* ${{ matrix.year }}/

      # Commit changes to repository
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add ${{ matrix.year }}
          git commit -m "Update content for year ${{ matrix.year }}" || echo "No changes to commit"
          git push